// apps/yourcandidates/pages/about.vue
<template>
  <div>
    <election-header />
    <HomePageBack />

    <div class="section-about">
      <h1>เกี่ยวกับโครงการ</h1>

      <h2>เป้าหมาย</h2>
      <p>
        การเลือกตั้ง คือกลไกตามระบอบประชาธิปไตย
        ที่เปิดโอกาสให้ประชาชนซึ่งเป็นเจ้าของอำนาจ เลือก ‘ผู้แทน’
        เข้าไปทำหน้าที่แทนตัวเอง ทุกๆ การเข้าคูหาและทุกๆ กากบาท
        จึงเป็นการตัดสินใจครั้งสำคัญ ว่าเราจะใช้อำนาจของเรา
        เพื่อเปลี่ยนแปลงสังคมและประเทศที่เราอยู่ไปในทิศทางไหน
      </p>
      <br />
      <p>
        โปรเจกต์ ‘เลือกตั้งรอบนี้มีอะไรให้เลือกบ้าง?’ นี้ พวกเรา WeVis
        จึงพยายามรวบรวมข้อมูลผู้สมัคร ทั้ง ส.ส. เขต (บัตรเลือกคน) และ ส.ส.
        บัญชีรายชื่อ (บัตรเลือกพรรค)
        มาให้ประชาชนผู้มีสิทธิเลือกตั้งอย่างพวกเราค้นหาได้ง่ายๆ
        และสามารถลิงก์ไปดูข้อมูลที่เกี่ยวข้องของแต่ละคน แต่ละพรรคได้อย่างสะดวก
      </p>
      <br />

      <p>
        ก่อนเข้าคูหา #เลือกตั้ง66 นี้
        พวกเราเลยออยากชวนทุกคนมาลองศึกษาข้อมูลให้ดี เพื่อตัดสินใจมอบอำนาจให้กับ
        ‘ผู้แทน’ ที่จะเข้าไปในรัฐสภาเพื่อใช้สิทธิและเสียงแทนเราอย่างแท้จริง
      </p>

      <h2>ที่มาของข้อมูล</h2>
      <ul>
        <li>
          เอกสารเผยแพร่ศูนย์อำนวยความสะดวกแก่สื่อมวลชน
          การรับสมัครรับเลือกตั้งสมาชิกสภาผู้แทนราษฎร เป็นการทั่วไป พ.ศ. 2566
        </li>
        <li>
          <a
            href="https://drive.google.com/drive/folders/11S_vXUR27TqM18s1823C8rjnmJhcv-rF"
            target="_blank"
            rel="noopener noreferrer"
            >ข้อมูลผู้สมัครรับเลือกตั้ง ส.ส.แบบบัญชีรายชื่อ</a
          >
        </li>
        <li>
          <a
            href="https://drive.google.com/drive/folders/1rI1oheUoQs16odp9LpoZuHHCwGxLKqfZ"
            target="_blank"
            rel="noopener noreferrer"
            >ข้อมูลผู้สมัครรับเลือกตั้ง ส.ส.แบบแบ่งเขตเลือกตั้ง</a
          >
        </li>
      </ul>

      <h2>นโยบายการนำข้อมูลไปใช้ต่อ</h2>
      <p>
        ทางทีมมีความตั้งใจที่พัฒนาทุกโปรเจ็กต์ให้เป็น Open Source
        และเปิดข้อมูลเป็น Open Data ภายใต้เงื่อนไข Creative Commons
        Attribution-NonCommercial License (CC-BY-NC)
        คือสามารถนำไปเผยแพร่และดัดแปลงได้ โดยต้องระบุที่มา
        แต่ห้ามนำไปใช้เพื่อการค้า สามารถดูรายละเอียดเพิ่มเติมได้ที่
        <a
          href="wevis.info/terms-of-use"
          target="_blank"
          rel="noopener noreferrer"
          >wevis.info/terms-of-use</a
        >
        <br /><br />
        หากมีข้อสงสัยต้องการสอบถามเพิ่มเติม
        ประสงค์แจ้งเปลี่ยนแปลงหรือเพิ่มเติมข้อมูลเพื่อความถูกต้อง
        หรือมีข้อเสนอแนะใดๆ สามารถติดต่อได้ที่ team [at] punchup.world
      </p>

      <h2>ทีมงานร่วมพัฒนา</h2>
      <div v-for="(group, i) in collaborators" :key="i">
        <h3>{{ group.role }}</h3>
        <div class="collaborators-list">
          <span
            v-for="(member, j) in group.members"
            :key="i * collaborators.length + j"
          >
            <a :href="member.url" target="_blank" rel="noopener noreferrer">{{
              member.name
            }}</a>
            <span v-if="j < group.members.length - 1">, </span>
          </span>
        </div>
      </div>

      <h2>หมายเหตุ</h2>
      <p>
        <a
          href="https://punchup.world/"
          target="_blank"
          rel="noopener noreferrer"
          >Punch Up</a
        >
        และ
        <a href="https://wevis.info/" target="_blank" rel="noopener noreferrer"
          >WeVis</a
        >
        ได้รับการสนับสนุนทุนในการดำเนินงานจาก
        <a href="https://www.ned.org/" target="_blank" rel="noopener noreferrer"
          >National Endowment for Democracy (NED)</a
        >
        ซึ่งนำมาใช้เป็นต้นทุนในการรวมรวมข้อมูล ออกแบบ พัฒนาเว็บไซต์ ประสานงาน
        บริหารจัดการ ตลอดจนการจัด Meetup เพื่อดำเนินโครงการ
      </p>

      <div class="button-list-section">
        <a
          class="button-rounded--black link-text"
          href="https://docs.google.com/spreadsheets/d/1ooBHq0DWCbpH2KhHRmC2kwn4nV6gQO40PEYlDL8woCY"
        >
          <div class="icon">
            <IconsDownload />
          </div>
          ดาวน์โหลดข้อมูล
        </a>
        <a
          class="button-rounded--black link-text"
          href="https://airtable.com/shryu4errnlj1LWsM"
          target="_blank"
        >
          <div class="icon">
            <IconsMail />
          </div>
          Feedback
        </a>
        <a
          class="button-rounded--black link-text"
          target="_blank"
          href="https://github.com/wevisdemo/thailand-election-2023/tree/main/apps/yourcandidates"
        >
          <div class="icon">
            <IconsGithub />
          </div>
          View on Github
        </a>
      </div>
    </div>

    <election-bottom index-path="/yourcandidates" />
    <election-footer />
  </div>
</template>

<script>
import {
  ElectionHeader,
  ElectionBottom,
  ElectionFooter,
} from '@thailand-election-2023/components'
export default {
  data() {
    return {
      collaborators: [
        {
          role: 'เขียนโปรแกรม',
          members: [
            {
              name: 'napatswift',
              url: 'https://github.com/napatswift',
            },
            {
              name: 'JaeAiKay',
              url: 'https://github.com/JaeAiKay',
            },
          ],
        },
        {
          role: 'ออกแบบ',
          members: [
            {
              name: 'Namsai Supavong',
              url: 'https://www.instagram.com/namsaisupavong/',
            },
          ],
        },
        {
          role: 'สืบค้นและรวบรวมข้อมูล',
          members: [
            {
              name: 'Thanisara GG',
              url: 'https://www.linkedin.com/in/thanisara-r/',
            },
            {
              name: 'Fhy Pantira',
              url: 'https://www.linkedin.com/in/pantira-monsumrith-b42018224/',
            },
          ],
        },
        {
          role: 'บรรณาธิการ',
          members: [
            {
              name: 'Thanisara GG',
              url: 'https://www.linkedin.com/in/thanisara-r/',
            },
          ],
        },
        {
          role: 'ประสานงานและจัดการอื่นๆ',
          members: [
            {
              name: 'Phy pantira',
              url: 'https://www.linkedin.com/in/pantira-monsumrith-b42018224/',
            },
            {
              name: 'Th1nkK1D',
              url: 'https://github.com/Th1nkK1D',
            },
          ],
        },
      ],
      links: {},
    }
  },
  components: {
    ElectionHeader,
    ElectionBottom,
    ElectionFooter,
  },
}
</script>

<style scoped>
.link-text {
  font-weight: 700;
  text-decoration: none !important;
  color: var(--color-black);
}

.button-rounded--black .icon {
  margin-right: 0.5rem;
}

.button-list-section {
  display: flex;
  flex-direction: column;
  justify-content: center;
  gap: 0.5rem;
  padding: 50px 0px;
}

@media (min-width: 560px) {
  .button-list-section {
    flex-direction: row;
  }
}
</style>

// apps/electionsim/src/routes/about/+page.svelte
<script lang="ts">
	import { base } from '$app/paths';
	import Metadata from '../../components/metadata.svelte';

	const sources = [
		['ผลการเลือกตั้ง 62', 'https://www.ect.go.th/ect_th/news_all.php?cid=26'],
		[
			'การแบ่งเขตเลือกตั้ง 66',
			'https://ratchakitcha.soc.go.th/documents/140A019N0000000002800.pdf',
		],
		[
			'ข้อมูลผู้สมัครรับเลือกตั้ง ส.ส.แบบบัญชีรายชื่อ',
			'https://drive.google.com/drive/folders/11S_vXUR27TqM18s1823C8rjnmJhcv-rF',
		],
		[
			'ข้อมูลผู้สมัครรับเลือกตั้ง ส.ส.แบบแบ่งเขตเลือกตั้ง',
			'https://drive.google.com/drive/folders/1rI1oheUoQs16odp9LpoZuHHCwGxLKqfZ',
		],
	];

	const contributers = [
		[
			'เขียนโปรแกรม',
			[
				['Th1nkK1D', 'https://github.com/Th1nkK1D'],
				['tesol2y090', 'https://github.com/tesol2y090'],
			],
		],
		['ออกแบบ', [['Tae Prasongpongchai', 'https://taepras.com/']]],
		[
			'สืบค้นและรวบรวมข้อมูล',
			[
				['Thanisara GG', 'https://www.linkedin.com/in/thanisara-r/'],
				[
					'Fhy Pantira',
					'https://www.linkedin.com/in/pantira-monsumrith-b42018224/',
				],
			],
		],
		[
			'บรรณาธิการ ',
			[['Thanisara GG', 'https://www.linkedin.com/in/thanisara-r/']],
		],
		[
			'ประสานงานและจัดการอื่นๆ ',
			[
				[
					'Fhy Pantira',
					'https://www.linkedin.com/in/pantira-monsumrith-b42018224/',
				],
			],
		],
	];
</script>

<Metadata pageTitle="เกี่ยวกับโครงการ" />

<election-header />

<div class="section-about">
	<h1>เกี่ยวกับโครงการ</h1>

	<h2>เป้าหมาย</h2>

	<p>
		การเลือกตั้ง คือกลไกตามระบอบประชาธิปไตย
		ที่เปิดโอกาสให้ประชาชนซึ่งเป็นเจ้าของอำนาจ เลือก ‘ผู้แทน’
		เข้าไปทำหน้าที่แทนตัวเอง ทุกๆ การเข้าคูหาและทุกๆ กากบาท
		จึงเป็นการตัดสินใจครั้งสำคัญ ว่าเราจะใช้อำนาจของเรา
		เพื่อเปลี่ยนแปลงสังคมและประเทศที่เราอยู่ไปในทิศทางไหน
	</p>
	<p>
		4 ปีนับจาก #เลือกตั้ง62 ปัจจัยหลายอย่างในการเมืองไทยเปลี่ยนไป
		ทั้งกติกาเลือกตั้ง กลยุทธ์ของพรรคต่างๆ และกระแสความนิยมของประชาชน
		ปัจจัยเหล่านี้ล้วนมีผลต่อผลการเลือกตั้ง 66 ที่กำลังจะเกิดขึ้น โปรเจกต์
		‘ทดลองเป็นนักวิเคราะห์ #เลือกตั้ง66' นี้ WeVis และ Beyond X
		เลยได้ลองนำปัจจัยเบื้องต้นเหล่านี้มาเป็นข้อสันนิษฐาน เพื่อให้ทุกคนค่อยๆ
		ทำความเข้าใจและสร้างบทสนทนาเกี่ยวกับการเลือกตั้งไปด้วยกัน
	</p>
	<p>
		ที่สำคัญ ก่อนเข้าคูหา #เลือกตั้ง66 นี้
		พวกเราเลยออยากชวนทุกคนมาลองศึกษาข้อมูลให้ดี เพื่อตัดสินใจมอบอำนาจให้กับ
		‘ผู้แทน’ ที่จะเข้าไปในรัฐสภาเพื่อใช้สิทธิและเสียงแทนเราอย่างแท้จริง
	</p>
	<p>
		<strong>Disclaimer</strong>:
		ผลการวิเคราะห์นี้เป็นเพียงการทดลองประมาณการแบบคร่าวๆ
		บนฐานข้อมูลผลการเลือกตั้งเดิมบนกติกาเลือกตั้งใหม่และข้อสันนิษฐานที่กำหนดไว้เท่านั้น
		อาจมีปัจจัยอื่นที่ส่งผลต่อผลลัพธ์ในการเลือกตั้ง
		และไม่ได้มีเจตนาในการชี้นำผลการเลือกตั้งแต่อย่างใด
	</p>

	<h2>ที่มาของข้อมูล</h2>

	<ul>
		{#each sources as [text, href]}
			<li>
				<a {href} target="_blank" rel="noopener noreferrer">{text}</a>
			</li>
		{/each}
	</ul>

	<h2>นโยบายการนำข้อมูลไปใช้ต่อ</h2>

	<p>
		ทางทีมมีความตั้งใจที่พัฒนาทุกโปรเจ็กต์ให้เป็น Open Source และเปิดข้อมูลเป็น
		Open Data ภายใต้เงื่อนไข Creative Commons Attribution-NonCommercial License
		(CC-BY-NC) คือสามารถนำไปเผยแพร่และดัดแปลงได้ โดยต้องระบุที่มา
		แต่ห้ามนำไปใช้เพื่อการค้า สามารถดูรายละเอียดเพิ่มเติมได้ที่ <a
			href="https://wevis.info/terms-of-use"
			target="_blank"
			rel="noopener noreferrer">wevis.info/terms-of-use</a
		>
	</p>

	<p>
		หากมีข้อสงสัยต้องการสอบถามเพิ่มเติม
		ประสงค์แจ้งเปลี่ยนแปลงหรือเพิ่มเติมข้อมูลเพื่อความถูกต้อง
		หรือมีข้อเสนอแนะใดๆ สามารถติดต่อได้ที่ <a href="mailto:team@punchup.world"
			>team [at] punchup.world</a
		>
	</p>

	<h2>ทีมงานร่วมพัฒนา</h2>

	{#each contributers as [role, people]}
		<h3>{role}</h3>

		{#each people as [name, href], i}
			{#if i > 0}
				{`, `}
			{/if}
			<a {href} target="_blank" rel="noopener noreferrer">{name}</a>
		{/each}
	{/each}

	<h2>หมายเหตุ</h2>

	<p>
		<a href="https://punchup.world" target="_blank" rel="noopener noreferrer"
			>Punch Up</a
		>
		และ
		<a href="https://wevis.info" target="_blank" rel="noopener noreferrer"
			>WeVis</a
		>
		ได้รับการสนับสนุนทุนในการดำเนินงานจาก
		<a href="https://www.ned.org" target="_blank" rel="noopener noreferrer"
			>National Endowment for Democracy (NED)</a
		> ซึ่งนำมาใช้เป็นต้นทุนในการรวมรวมข้อมูล ออกแบบ พัฒนาเว็บไซต์ ประสานงาน บริหารจัดการ
		ตลอดจนการจัด Meetup เพื่อดำเนินโครงการ
	</p>

	<div class="flex flex-col md:flex-row justify-center my-12 gap-2 w-full">
		<a
			href="https://github.com/wevisdemo/thailand-election-2023/tree/main/apps/electionsim/static/data"
			target="_blank"
			rel="noopener noreferrer"
			class="button-rounded--black flex-1"
			><svg width="20" height="21" viewBox="0 0 20 21" fill="none">
				<path
					d="M5.82929 4.80389C5.50108 4.80389 4.97893 4.80389 4.66029 4.80389C4.15801 4.80389 2.09968 4.721 2.09968 4.721C2.09968 5.28424 2.09968 6.9894 2.09968 6.9894V13.4476C2.09968 13.4476 2.01886 17.2106 2.01886 17.5346C2.01886 17.9599 1.88438 18.3245 2.33362 18.3245C3.50134 18.3245 4.66221 18.4122 5.83001 18.4122C6.66186 18.4122 7.48799 18.3245 8.31832 18.3245C10.0004 18.3245 11.648 18.5 13.3375 18.5C14.2767 18.5 15.1824 18.4122 16.1235 18.4122C16.4638 18.4122 17.5912 18.4413 17.9315 18.4413L17.8675 13.5852C17.8675 13.0952 17.7305 12.3108 17.9057 11.8689C18.0925 11.3979 17.944 10.5151 17.944 9.98686C17.944 9.34325 17.944 8.69965 17.944 8.05604C17.944 6.9743 17.8675 5.88581 17.8675 4.82827C17.8675 4.27284 17.0647 4.57943 16.7233 4.62836C16.4236 4.67129 16.1023 4.63323 15.8003 4.63323C15.1539 4.63323 15.473 4.721 14.8096 4.721"
					stroke="currentColor"
					stroke-width="2"
					stroke-linecap="round"
					stroke-linejoin="round"
				/>
				<path
					d="M9.80105 2.67639C10.1899 4.76806 9.90313 8.73316 9.8438 10.8192C9.84082 10.9239 9.8164 13.4712 9.92415 13.4938C10.0691 13.5242 10.6725 12.8414 10.7107 12.8063C11.4069 12.1675 12.4385 11.8292 13.1129 11.1675C13.7774 10.5155 14.3976 9.83678 15.0346 9.16151C15.0882 9.10467 15.247 8.83838 15.0898 9.01714C14.3301 9.88118 13.5085 10.7718 12.6963 11.5841C12.3047 11.9757 11.6003 12.6779 11.153 13.2487C10.8318 13.8 10.1251 14.446 9.80105 14.9944C9.65815 15.2362 9.44673 14.6667 9.36501 14.5583C8.5224 13.441 7.72888 12.3624 6.98962 11.1761C6.40413 10.2366 5.91628 9.3136 5.1297 8.52701"
					stroke="currentColor"
					stroke-width="2"
					stroke-linecap="round"
				/>
			</svg>
			<span>ดาวน์โหลดข้อมูล</span></a
		>
		<a
			href="https://airtable.com/shryu4errnlj1LWsM"
			target="_blank"
			rel="noopener noreferrer"
			class="button-rounded--black flex-1"
			><svg
				width="20"
				height="21"
				viewBox="0 0 20 21"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
			>
				<path
					d="M2.34052 5.24893C0.990493 5.61974 1.65884 12.6481 1.65884 13.9449C1.65884 14.5263 1.3545 16.4525 2.07542 16.483C3.86205 16.5585 5.66478 16.483 7.45311 16.483C9.87429 16.483 12.4451 16.8574 14.9516 16.8574C18.0191 16.8574 18.3446 17.4252 18.0191 14.4141C18.0191 11.4111 17.9105 9.38873 18.0191 7.12127C18.0652 6.1603 18.9559 5.24893 17.5268 5.24893C16.094 5.24893 14.6612 5.24893 13.2285 5.24893C11.1266 5.24893 9.02476 5.24893 6.92292 5.24893C5.70828 5.24893 3.42077 5.09341 2.34052 4.5"
					stroke="currentColor"
					stroke-width="2"
					stroke-linecap="round"
				/>
				<path
					d="M1 5.16876C1.64166 5.25688 2.07452 6.16242 2.6 6.53599C3.28438 7.02251 4.21489 7.75544 4.82222 8.36709C5.72478 9.27606 6.92094 9.92055 7.93333 10.6621C8.63412 11.1754 9.3627 11.7443 10.0889 12.2002C10.4838 12.4481 11.6455 11.2596 12.0778 11.0039C13.0329 10.4389 13.8482 9.53818 14.8444 9.07512C16.3333 8.38305 17.451 6.61498 19 6.04769"
					stroke="currentColor"
					stroke-width="2"
					stroke-linecap="round"
				/>
			</svg>
			<span>Feedback</span></a
		>
		<a
			href="https://github.com/wevisdemo/thailand-election-2023/tree/main/apps/electionsim"
			target="_blank"
			rel="noopener noreferrer"
			class="button-rounded--black flex-1"
			><svg
				width="20"
				height="20"
				viewBox="0 0 20 20"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
			>
				<path
					fill-rule="evenodd"
					clip-rule="evenodd"
					d="M10.0127 0.5359C7.63574 0.533547 5.3356 1.35605 3.52448 2.85603C1.71336 4.356 0.509647 6.43539 0.129065 8.72156C-0.251517 11.0077 0.215908 13.3512 1.44756 15.3321C2.67922 17.313 4.59461 18.8017 6.85047 19.5316C7.34783 19.6213 7.53204 19.3162 7.53204 19.0589C7.53204 18.8017 7.53204 18.2154 7.53204 17.4017C4.75049 18 4.16102 16.0974 4.16102 16.0974C3.97568 15.5078 3.58192 15.0011 3.04963 14.6675C2.14701 14.0692 3.12331 14.0692 3.12331 14.0692C3.43972 14.1128 3.74181 14.2259 4.0067 14.4C4.2716 14.5742 4.49235 14.8048 4.65225 15.0743C4.78811 15.3144 4.97127 15.5259 5.19124 15.6968C5.4112 15.8677 5.66364 15.9946 5.93406 16.0702C6.20447 16.1458 6.48754 16.1686 6.76704 16.1373C7.04653 16.1061 7.31693 16.0214 7.56273 15.888C7.60127 15.3958 7.81904 14.9333 8.17676 14.5837C5.95398 14.3384 3.62068 13.5008 3.62068 9.76751C3.60541 8.80007 3.97256 7.86395 4.6461 7.15298C4.34552 6.31189 4.38059 5.39142 4.74435 4.57436C4.74435 4.57436 5.58556 4.31111 7.49519 5.5735C9.135 5.13481 10.8658 5.13481 12.5057 5.5735C14.4153 4.31111 15.2504 4.57436 15.2504 4.57436C15.6179 5.39025 15.6552 6.31141 15.3548 7.15298C16.0283 7.86395 16.3954 8.80007 16.3802 9.76751C16.3802 13.5128 14.0407 14.3325 11.8118 14.5538C12.0508 14.7879 12.2354 15.0694 12.353 15.379C12.4706 15.6887 12.5184 16.0194 12.4934 16.3487C12.4934 17.653 12.4934 18.706 12.4934 19.0231C12.4934 19.3401 12.6715 19.5854 13.1811 19.4957C15.4299 18.759 17.3369 17.2678 18.5621 15.2883C19.7873 13.3087 20.2509 10.9694 19.8704 8.68772C19.4898 6.40599 18.2897 4.33017 16.4842 2.83053C14.6787 1.33089 12.3852 0.504941 10.0127 0.5V0.5359Z"
					fill="currentColor"
				/>
			</svg>
			<span>View on Github</span></a
		>
	</div>
</div>

<election-bottom index-path={base} about-path="{base}/about" />
<election-footer />

<style lang="postcss">
	p {
		@apply mt-4;
	}

	a.button-rounded--black {
		@apply no-underline text-current;
	}
</style>
